version: "3.8"
services:
  mysqldb:
    image: mysql:8.0.36
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devops_DB
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app-tpfoyer:
    depends_on:
      - mysqldb
    image: sirine850/tp-foyer:5.0.0
    #build : ./
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
      
      "spring.datasource.url"="jdbc:mysql://localhost:3306/devops_DB?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC",
      "spring.datasource.username"="root",
      "spring.datasource.password"="root",
      "spring.jpa.hibernate.ddl-auto" : "update"
      }'


    stdin_open: true
    tty: true

volumes:
  db :